name: 'Setup Machine'
description: Sets up all dependencies for builds
runs:
  using: "composite"
  steps:
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: 'global.json'

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install Dev Certs
      shell: bash
      run: |
        echo "SSL_CERT_DIR=$HOME/.aspnet/dev-certs/trust:/usr/lib/ssl/certs" >> "$GITHUB_ENV"
        export SSL_CERT_DIR="$HOME/.aspnet/dev-certs/trust:/usr/lib/ssl/certs"
        dotnet dev-certs https --trust
    
    - name: Prepare Build
      shell: bash
      run: ${{ github.workspace }}/scripts/prepare-build.sh