<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Humanizer" Version="3.0.10" />
    <PackageReference
      Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions"
      Version="$(MicrosoftPackageVersion)"
    />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Devices\Resolvers\DefaultDeviceTypeOptions.json">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </EmbeddedResource>
  </ItemGroup>
</Project>
