version: "3.9"
services:
  haus_mqtt:
    container_name: haus_mqtt
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./haus_mqtt/config:/mosquitto/config
      - ./haus_mqtt/data:/mosquitto/data
      - ./haus_mqtt/log:/mosquitto/log

  haus_zigbee:
    container_name: haus_zigbee
    restart: always
    image: bryceklinker/personal:haus-zigbee-latest
    environment:
      - "Haus:Server=mqtt://haus_mqtt:1883"
      - "Zigbee:Config:Mqtt:Server=mqtt://haus_mqtt:1883"
    links:
      - haus_mqtt
    volumes:
      - ./haus_zigbee2mqtt:/app/data
      - ./haus_zigbee2mqtt/logs:/app/haus-logs

  haus_web:
    container_name: haus_web
    restart: always
    image: bryceklinker/personal:haus-web-latest
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./haus_web:/app/data
      - ./haus_web/logs:/app/haus-logs
      - ./cert.pfx:/https/cert.pfx
    environment:
      - "Mqtt:Server=mqtt://haus_mqtt:1883"
      - "Database:ConnectionString=Data Source=./data/haus.db;"
      - "ASPNETCORE_URLS=https://+;http://+"
      - "ASPNETCORE_HTTPS_PORT=443"
      - "ASPNETCORE_ENVIRONMENT=Production"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=password"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx"
    links:
      - haus_mqtt

  zigbee2mqtt:
    container_name: haus_zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: always
    environment:
      - TZ=America/Chicago
    links:
      - haus_mqtt
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./haus_zigbee2mqtt:/app/data
      - ./configuration.yaml:/app/data/configuration.yaml
      - /run/udev:/runudev:ro