<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(MicrosoftPackageVersion)"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftPackageVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Haus.Cqrs\Haus.Cqrs.csproj"/>
    </ItemGroup>

</Project>
