permit_join: true
mqtt:
  base_topic: haus
  server: 'mqtt://localhost'
  serial:
    adapter: deconz
advanced:
  log_level: debug
devices:
  '0x00124b001f6fc6b4':
    friendly_name: '0x00124b001f6fc6b4'
