#!/usr/bin/env bash
set -ex

export CYPRESS_AUTH_PASSWORD="${AUTH_PASSWORD}"
export CYPRESS_AUTH_USERNAME="${AUTH_USERNAME}"
export CYPRESS_AUTH_DOMAIN="${AUTH_DOMAIN}"
export CYPRESS_AUTH_AUDIENCE="${AUTH_AUDIENCE}"
export CYPRESS_AUTH_CLIENT_ID="${AUTH_CLIENT_ID}"
export CYPRESS_AUTH_CLIENT_SECRET="${AUTH_CLIENT_SECRET}"
export IS_RELEASE=${IS_RELEASE:-false}
export VERSION=${VERSION:-"v0.0.0"}
export VERSION=${VERSION:1}
WORKING_DIRECTORY=$(pwd)
export WORKING_DIRECTORY
export CONFIGURATION=${CONFIGURATION:-'Release'}
export PUBLISH_DIRECTORY="${WORKING_DIRECTORY}/publish"
export COVERAGE_FILE_PATH="${WORKING_DIRECTORY}/coverage.json"
export REPORT_COVERAGE_FILE_PATH="${WORKING_DIRECTORY}/coverage.cobertura.xml"

export WEB_HOST_PUBLISH_DIRECTORY="${PUBLISH_DIRECTORY}/haus-web"
export WEB_HOST_BASE_ASSET_PATH="Haus.Web.Host"
export WEB_HOST_PROJECT="${WORKING_DIRECTORY}/src/Haus.Web.Host/Haus.Web.Host.csproj"

export ZIGBEE_HOST_PUBLISH_DIRECTORY="${PUBLISH_DIRECTORY}/haus-zigbee"
export ZIGBEE_HOST_BASE_ASSET_PATH="Haus.Zigbee.Host"
export ZIGBEE_HOST_PROJECT="${WORKING_DIRECTORY}/src/Haus.Zigbee.Host/Haus.Zigbee.Host.csproj"
