#!/usr/bin/env bash
set -ex

export CYPRESS_AUTH_PASSWORD="${AUTH_PASSWORD}"
export CYPRESS_AUTH_USERNAME="${AUTH_USERNAME}"
export CYPRESS_AUTH_DOMAIN="${AUTH_DOMAIN}"
export CYPRESS_AUTH_AUDIENCE="${AUTH_AUDIENCE}"
export CYPRESS_AUTH_CLIENT_ID="${AUTH_CLIENT_ID}"
export CYPRESS_AUTH_CLIENT_SECRET="${AUTH_CLIENT_SECRET}"
IS_RELEASE=${IS_RELEASE:-false}
VERSION=${VERSION:-"v0.0.0"}
VERSION=${VERSION:1}
WORKING_DIRECTORY=$(pwd)
CONFIGURATION=${CONFIGURATION:-'Release'}
PUBLISH_DIRECTORY="${WORKING_DIRECTORY}/publish"
COVERAGE_FILE_PATH="${WORKING_DIRECTORY}/coverage.json"
REPORT_COVERAGE_FILE_PATH="${WORKING_DIRECTORY}/coverage.cobertura.xml"

WEB_HOST_PROJECT="${WORKING_DIRECTORY}/src/Haus.Web.Host/Haus.Web.Host.csproj"
ZIGBEE_HOST_PROJECT="${WORKING_DIRECTORY}/src/Haus.Zigbee.Host/Haus.Zigbee.Host.csproj"

WEB_HOST_BASE_ASSET_PATH="Haus.Web.Host"
ZIGBEE_HOST_BASE_ASSET_PATH="Haus.Zigbee.Host"