on: [push]
env:
  YARN_VERSION: "1.22.4"


jobs:
  ci:
    name: Continuous Integration
    runs-on: macos-10.15

    strategy:
      matrix:
        node-version: [12.14.1]
        dotnet-version: [3.1.200]
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Unit Tests
        run: ./scripts/run_unit_tests.sh

      - name: Acceptance Tests
        run: ./scripts/run_acceptance_tests.sh
