name: Main
on:
  push:
    branches:
      - main
  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    env:
      IS_RELEASE: ${{ github.event.inputs.is_release || false }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
      AUTH_USERNAME: ${{ secrets.AUTH_USERNAME }}
      AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
      AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
      AUTH_AUDIENCE: ${{ secrets.AUTH_AUDIENCE }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_REPO: personal
      LOG_LEVEL: Warning
    steps:
      - name: Clone
        uses: actions/checkout@v4
      
      - name: Setup Machine
        uses: ${{ github.workspace }}/.github/actions/setup-machine

      - name: Prepare Build
        run: ./scripts/prepare-build.sh

      - name: Run Unit Tests
        run: ./scripts/run-unit-tests.sh

      - name: Run Acceptance Tests
        run: ./scripts/run-acceptance-tests.sh