name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      is_release:
        description: 'Is this a release?'
        required: false
        default: false
      version_bump:
        description: 'What kind of release is this?'
        required: false
        default: patch
jobs:
  continuous_integration:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.x'

      - name: Start MQTT Server
        uses: namoshek/mosquitto-github-action@v0.1.0
        with:
          version: '1.6'

      - name: Bump version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.version_bump }}
        if: ${{ github.event.inputs.is_release }}

      - name: Run Build Script
        run: ./scripts/build.sh
        env:
          IS_RELEASE: ${{ github.event.inputs.is_release || false }}
          VERSION: ${{ steps.tag_version.outputs.new_tag }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
        if: ${{ github.event.inputs.is_release }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/Haus.Web.Host.linux-x64.zip
          asset_name: Haus.Web.Host.linux-x64.zip
          asset_content_type: application/zip
        if: ${{ github.event.inputs.is_release }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/Haus.Zigbee.Host.linux-x64.zip
          asset_name: Haus.Zigbee.Host.linux-x64.zip
          asset_content_type: application/zip
        if: ${{ github.event.inputs.is_release }}